"""sprint3 files and grading history

Revision ID: 47a72debb3e0
Revises: 34eb526df2c3
Create Date: 2026-06-04 21:56:59.853583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "47a72debb3e0"  # keep autogenerated value, do not change
down_revision: Union[str, None] = "34eb526df2c3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "submission_files",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("submission_id", sa.Uuid(), nullable=False),
        sa.Column("file_path", sa.Text(), nullable=False),
        sa.Column("mime_type", sa.String(length=120), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["submission_id"], ["submissions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_submission_files_submission_id"),
        "submission_files",
        ["submission_id"],
        unique=False,
    )

    op.create_table(
        "grading_attempts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("submission_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("score", sa.Integer(), nullable=True),
        sa.Column("feedback", sa.Text(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("model_name", sa.String(length=120), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('graded','failed')", name="ck_grading_attempts_status"
        ),
        sa.CheckConstraint(
            "score IS NULL OR score BETWEEN 0 AND 100",
            name="ck_grading_attempts_score",
        ),
        sa.ForeignKeyConstraint(["submission_id"], ["submissions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_grading_attempts_submission_id"),
        "grading_attempts",
        ["submission_id"],
        unique=False,
    )
    op.create_index(
        "ix_grading_attempts_submission_created",
        "grading_attempts",
        ["submission_id", sa.text("created_at DESC")],
        unique=False,
    )

    # Backfill: existing graded submissions become a single grading_attempts row.
    op.execute(
        """
        INSERT INTO grading_attempts
            (id, submission_id, status, score, feedback, error_message, model_name, created_at)
        SELECT
            gen_random_uuid(),
            id,
            'graded',
            score,
            ai_feedback,
            NULL,
            'claude-sonnet-4-5 (backfilled)',
            COALESCE(graded_at, submitted_at)
        FROM submissions
        WHERE score IS NOT NULL
        """
    )


def downgrade() -> None:
    op.drop_index(
        "ix_grading_attempts_submission_created", table_name="grading_attempts"
    )
    op.drop_index(
        op.f("ix_grading_attempts_submission_id"), table_name="grading_attempts"
    )
    op.drop_table("grading_attempts")
    op.drop_index(
        op.f("ix_submission_files_submission_id"), table_name="submission_files"
    )
    op.drop_table("submission_files")
