"""sprint4 admin comments notifications

Adds:
- users.is_admin (NOT NULL DEFAULT false; existing rows backfill via the
  server_default so no separate UPDATE is needed)
- instructor_comments (FK to submissions CASCADE / to author RESTRICT)
- notifications (FK to recipient CASCADE / to sender RESTRICT)

The autogenerated drop of `ix_grading_attempts_submission_created` was
removed by hand — that index was created in Sprint 3 but never declared
on the model. Adding it to GradingAttempt.__table_args__ in this same
sprint quiets the autogenerator.

Revision ID: af4220e315e6
Revises: 47a72debb3e0
Create Date: 2026-06-06 19:40:20.187265
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "af4220e315e6"
down_revision: Union[str, None] = "47a72debb3e0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "notifications",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("recipient_user_id", sa.Uuid(), nullable=False),
        sa.Column("sender_user_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("link", sa.String(length=500), nullable=True),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["recipient_user_id"], ["users.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["sender_user_id"], ["users.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_notifications_recipient_user_id"),
        "notifications",
        ["recipient_user_id"],
        unique=False,
    )

    op.create_table(
        "instructor_comments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("submission_id", sa.Uuid(), nullable=False),
        sa.Column("author_user_id", sa.Uuid(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_user_id"], ["users.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["submission_id"], ["submissions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_instructor_comments_submission_id"),
        "instructor_comments",
        ["submission_id"],
        unique=False,
    )

    op.add_column(
        "users",
        sa.Column(
            "is_admin",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
    )


def downgrade() -> None:
    op.drop_column("users", "is_admin")
    op.drop_index(
        op.f("ix_instructor_comments_submission_id"),
        table_name="instructor_comments",
    )
    op.drop_table("instructor_comments")
    op.drop_index(
        op.f("ix_notifications_recipient_user_id"), table_name="notifications"
    )
    op.drop_table("notifications")
